In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import joblib

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
df=pd.DataFrame(data.data,columns=data.feature_names)

In [6]:
data.target#species is the target column it's data have three classes setosa,viriginca and versicolor stored as a label encoder

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
df['target']=data.target

In [8]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [9]:
data .target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
df['target_names']=df['target'].map({i:name for i,name in enumerate(data.target_names)})

In [11]:
df['target_names']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target_names, Length: 150, dtype: object

In [12]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_names  
0       0       setosa  
1       0       setosa  
2       0       setosa  
3       0       setosa  
4       0       setosa

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [15]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [16]:
df['target_names'].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [17]:
binary_df=df[df['target']!=2]

In [18]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [19]:
x_binary=binary_df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]

In [20]:
y_binary=binary_df[['target']]

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x_binary,y_binary, test_size=0.2)

In [22]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.490000          3.158750           2.753750   
std             0.652861          0.480162           1.441338   
min             4.300000          2.200000           1.000000   
25%             5.000000          2.800000           1.500000   
50%             5.400000          3.150000           1.700000   
75%             5.925000          3.500000           4.225000   
max             7.000000          4.400000           5.000000   

       petal width (cm)  
count         80.000000  
mean           0.745000  
std            0.559136  
min            0.100000  
25%            0.200000  
50%            0.400000  
75%            1.300000  
max            1.800000

In [23]:
x_binary.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         100.000000        100.000000         100.000000   
mean            5.471000          3.099000           2.861000   
std             0.641698          0.478739           1.449549   
min             4.300000          2.000000           1.000000   
25%             5.000000          2.800000           1.500000   
50%             5.400000          3.050000           2.450000   
75%             5.900000          3.400000           4.325000   
max             7.000000          4.400000           5.100000   

       petal width (cm)  
count        100.000000  
mean           0.786000  
std            0.565153  
min            0.100000  
25%            0.200000  
50%            0.800000  
75%            1.300000  
max            1.800000

In [24]:
scaler=StandardScaler()
x_train = scaler.fit_transform(x_train)

In [25]:
x_test=scaler.transform(x_test)

In [26]:
svm_binary=SVC(kernel='linear',C=1.0,probability=True)

In [27]:
svm_binary.fit(x_train,y_train)

f:\study material\data science\euroncourse\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', probability=True)

In [28]:
svm_binary.predict(x_test)

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [29]:
print("binary class classification report:\n",classification_report(y_test,svm_binary.predict(x_test)))

binary class classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        13

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [30]:
confusion_matrix(y_test,svm_binary.predict(x_test))

array([[ 7,  0],
       [ 0, 13]])

In [31]:
joblib.dump(svm_binary,'svm_binary.pkl')

['svm_binary.pkl']

In [32]:
x_multi = df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]

In [33]:
x_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [34]:
y_multi=df['target']

In [35]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [36]:
x_train_multi,x_test_multi,y_train_multi,y_test_multi = train_test_split(x_multi,y_multi,test_size=0.2)

In [37]:
svm_multi=SVC(kernel='linear',probability=True)

In [38]:
svm_multi.fit(x_train_multi,y_train_multi)

SVC(kernel='linear', probability=True)

In [39]:
svm_multi.predict(x_test_multi)

array([1, 2, 1, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 1, 1, 1,
       2, 0, 2, 1, 2, 1, 2, 2])

In [40]:
print("report for multi class svc \n",classification_report(y_test_multi,svm_multi.predict(x_test_multi)))

report for multi class svc 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        15

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [41]:
confusion_matrix(y_test_multi,svm_multi.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0,  7,  0],
       [ 0,  0, 15]])

In [42]:
joblib.dump(svm_multi,"svm_multi.pkl")

['svm_multi.pkl']

In [43]:
#this is a binary data
x_train,x_test,y_train,y_test

(array([[ 0.78610528,  0.50560474,  1.21919212,  1.53879305],
        [-1.0635542 , -0.33270364, -0.94515753, -1.16084388],
        [-0.13872446,  0.50560474, -0.8753398 , -0.62091649],
        [ 2.17334989, -0.12312654,  1.49846304,  1.35881725],
        [-0.44700104,  0.50560474, -0.94515753, -0.98086808],
        [-1.21769249,  0.08645055, -1.01497526, -0.98086808],
        [-0.75527762,  0.50560474, -0.80552207, -0.62091649],
        [ 0.01541383, -1.38058912,  0.87010347,  0.99886566],
        [ 0.4778287 ,  1.76306732, -1.08479299, -0.98086808],
        [ 0.32369041, -1.17101202,  0.52101481,  0.45893828],
        [-0.90941591, -0.12312654, -0.8753398 , -0.98086808],
        [ 1.86507331, -0.12312654,  1.35882758,  1.35881725],
        [-0.75527762,  0.50560474, -0.8753398 , -0.98086808],
        [ 0.01541383, -1.17101202,  1.14937439,  0.81888987],
        [-1.0635542 ,  0.50560474, -0.59606887, -0.98086808],
        [-0.60113933,  0.50560474, -0.8753398 , -0.98086808],
        

In [44]:
joblib.dump(scaler,'scaler.pkl')

['scaler.pkl']

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
x_train

array([[ 0.78610528,  0.50560474,  1.21919212,  1.53879305],
       [-1.0635542 , -0.33270364, -0.94515753, -1.16084388],
       [-0.13872446,  0.50560474, -0.8753398 , -0.62091649],
       [ 2.17334989, -0.12312654,  1.49846304,  1.35881725],
       [-0.44700104,  0.50560474, -0.94515753, -0.98086808],
       [-1.21769249,  0.08645055, -1.01497526, -0.98086808],
       [-0.75527762,  0.50560474, -0.80552207, -0.62091649],
       [ 0.01541383, -1.38058912,  0.87010347,  0.99886566],
       [ 0.4778287 ,  1.76306732, -1.08479299, -0.98086808],
       [ 0.32369041, -1.17101202,  0.52101481,  0.45893828],
       [-0.90941591, -0.12312654, -0.8753398 , -0.98086808],
       [ 1.86507331, -0.12312654,  1.35882758,  1.35881725],
       [-0.75527762,  0.50560474, -0.8753398 , -0.98086808],
       [ 0.01541383, -1.17101202,  1.14937439,  0.81888987],
       [-1.0635542 ,  0.50560474, -0.59606887, -0.98086808],
       [-0.60113933,  0.50560474, -0.8753398 , -0.98086808],
       [ 0.78610528, -2.

In [47]:
logistics_binary = LogisticRegression()
logistics_binary.fit(x_train,y_train)

f:\study material\data science\euroncourse\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [48]:
logistics_binary.predict(x_test)

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [49]:
print("classification report \n",classification_report(y_test,logistics_binary.predict(x_test)))

classification report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        13

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [50]:
confusion_matrix(y_test,logistics_binary.predict(x_test))

array([[ 7,  0],
       [ 0, 13]])

In [51]:
joblib.dump(logistics_binary,"logistics_binary.pkl")

['logistics_binary.pkl']

In [52]:
logistics_ovr = LogisticRegression(multi_class='ovr',solver='lbfgs',max_iter=2000)

In [53]:
logistics_ovr.fit(x_train_multi,y_train_multi)

f:\study material\data science\euroncourse\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='ovr')

In [54]:
logistics_ovr.predict(x_test_multi)

array([1, 2, 1, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 1, 1, 1,
       2, 0, 2, 2, 2, 1, 2, 2])

In [55]:
print("classification report \n",classification_report(y_test_multi,logistics_ovr.predict(x_test_multi)))

classification report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.86      0.92         7
           2       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.98      0.95      0.96        30
weighted avg       0.97      0.97      0.97        30



In [56]:
confusion_matrix(y_test_multi,logistics_ovr.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0,  6,  1],
       [ 0,  0, 15]])

In [57]:
joblib.dump(logistics_ovr,'logistics_ovr.pkl')

['logistics_ovr.pkl']

In [58]:
logistics_multinomial = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=2000)

In [59]:
logistics_multinomial.fit(x_train_multi,y_train_multi)

f:\study material\data science\euroncourse\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='multinomial')

In [60]:
logistics_multinomial.predict(x_test_multi)

array([1, 2, 1, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 1, 1, 1,
       2, 0, 2, 2, 2, 1, 2, 2])

In [61]:
confusion_matrix(y_test_multi,logistics_multinomial.predict(x_test_multi))

array([[ 8,  0,  0],
       [ 0,  6,  1],
       [ 0,  0, 15]])

In [62]:
print("classification report for multinomial logistics is \n",classification_report(y_test_multi,logistics_multinomial.predict(x_test_multi)))

classification report for multinomial logistics is 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.86      0.92         7
           2       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.98      0.95      0.96        30
weighted avg       0.97      0.97      0.97        30



In [63]:
joblib.dump(logistics_multinomial,'logistics_multinomial.pkl')

['logistics_multinomial.pkl']

In [64]:
#try to build a streamlit aap on this class discussion where we have built 5 models svc binary,svc multi,logistics binary,logistics ovr,logistics multinomial

In [65]:
#deploying these model by creating a streamlit app in that app u are suppose to give an option for model selection , then pass data through ui,get the prediction classname

In [66]:
!pip install matplotlib